/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author binh0
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienLogin
     */
    public Home() {
        initComponents();
        this.setIconImage(new ImageIcon("src/IMG/icon game.png").getImage());
        this.setTitle("Caro Game");
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setResizable(false);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boardClient = new javax.swing.JButton();
        boardAI = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ratings = new javax.swing.JButton();
        hd = new javax.swing.JButton();
        register = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game Caro");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boardClient.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boardClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_circled_play_24px.png"))); // NOI18N
        boardClient.setText("CHƠI NGAY    ");
        boardClient.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        boardClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boardClientActionPerformed(evt);
            }
        });
        getContentPane().add(boardClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 150, 30));

        boardAI.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boardAI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ICON HOME 3.png"))); // NOI18N
        boardAI.setText("CHƠI VỚI MÁY");
        boardAI.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        boardAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boardAIActionPerformed(evt);
            }
        });
        getContentPane().add(boardAI, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 150, 30));

        exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_exit_sign_24px.png"))); // NOI18N
        exit.setText("THOÁT GAME");
        exit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 150, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/LOGO HOME.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 160, 150));

        ratings.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ratings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ICONHOM2.png"))); // NOI18N
        ratings.setText("THÀNH TÍCH ");
        ratings.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ratings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratingsActionPerformed(evt);
            }
        });
        getContentPane().add(ratings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 140, 50));

        hd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ICONHOME4.png"))); // NOI18N
        hd.setText("CÁCH CHƠI");
        hd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hdActionPerformed(evt);
            }
        });
        getContentPane().add(hd, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 160, 50));

        register.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_login_32px.png"))); // NOI18N
        register.setText("ĐĂNG KÝ");
        register.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 130, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hdActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(rootPane, "Luật chơi: luật quốc tế 5 nước chặn 2 đầu\n"
                + "Hai người chơi luân phiên nhau chơi trước\n"
                + "Với mỗi ván chơi thắng bạn có thêm 20 điểm, nếu hòa bạn được thêm -10 điểm,\n"
                + "Chúc bạn chơi game vui vẻ <3");
                                             
    }//GEN-LAST:event_hdActionPerformed

    private void boardClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boardClientActionPerformed
        Graft ghep = new Graft();
          ghep.setVisible(true);

    // Ẩn JFrame hiện tại (JFrame Menu)
    this.setVisible(false);   // TODO add your handling code here:
    }//GEN-LAST:event_boardClientActionPerformed

    private void boardAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boardAIActionPerformed
        // TODO add your handling code here:
        BoardAI board = new BoardAI();
    board.setVisible(true);

    // Ẩn JFrame hiện tại (JFrame Menu)
    this.setVisible(false);
    }//GEN-LAST:event_boardAIActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        int confirmed = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn thoát chương trình?", "Xác nhận kết thúc chương trình", JOptionPane.YES_NO_OPTION);

    if (confirmed == JOptionPane.YES_OPTION) {
        // Kết thúc chương trình
        System.exit(0);
    }
    }//GEN-LAST:event_exitActionPerformed

    private void ratingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratingsActionPerformed
        // TODO add your handling code here:
       Ratings Ratings = new Ratings();
       Ratings.setVisible(true);

    // Ẩn JFrame hiện tại (JFrame Menu)
    this.setVisible(false);

    }//GEN-LAST:event_ratingsActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        Register Register = new Register();
        Register.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boardAI;
    private javax.swing.JButton boardClient;
    private javax.swing.JButton exit;
    private javax.swing.JButton hd;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton ratings;
    private javax.swing.JButton register;
    // End of variables declaration//GEN-END:variables
}
